"""
Django settings for telms project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
import json
import os

from django.contrib.messages import constants as messages
from django.core.exceptions import ImproperlyConfigured

# 1. APPLICATION DEFINITION

site_secrets = json.loads(os.environ.get('SITE_SECRETS', '{}'))


def environment(key: str, default: object = None) -> object:
    """
    Try to load a value from the environment or json secret.

    Prioritizes environment first.
    """
    if key in os.environ.keys():
        return os.environ.get(key)
    if key in site_secrets.keys():
        return site_secrets.get(key)

    # If it's not found anywhere, return the default value
    if(default is None):
        raise ImproperlyConfigured("No default specified for {}".format(key))

    return default


BASE_DIR = os.path.dirname(
    os.path.dirname(
        os.path.dirname(
            os.path.abspath(__file__))))

BASE_URL = environment('BASE_URL', 'localhost:8000')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = environment('SECRET_KEY')

ALLOWED_HOSTS = ["*"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
PRODUCTION = False

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'adminsortable2',
    'external',
    'crispy_forms',
    'rest_framework'
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'imagetext.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'imagetext/templates'),
                 os.path.join(BASE_DIR, 'external/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'imagetext.wsgi.application'


# 2. DATABASE

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': environment('IMAGETEXT_DB_NAME', 'imagetext_prod'),
        'USER': environment('IMAGETEXT_DB_USER', 'root'),
        'PASSWORD': environment('IMAGETEXT_DB_PASSWORD', ''),
        'HOST': environment('IMAGETEXT_DB_HOST', 'localhost'),
        'PORT': '3306',
    }
}


# 3. STATIC FILES (CSS, JavaScript, Images)

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'imagetext', 'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# 4. SECURITY SETTINGS

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

ADMINS = []


# 5. PACKAGE-SPECIFIC SETTINGS

# Crispy Forms
MESSAGE_TAGS = {
    messages.DEBUG: 'info',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}


# 6. INTERNATIONALIZATION

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# 7. EMAIL SETTINGS
# 8. EXTERNAL API SETTINGS
# 9. REDIS SETTINGS

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://{}:6379/{}".format(
            environment('REDIS_HOST', 'redis'),
            environment('REDIS_DB', 1)
        ),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

CACHE_TTL = 604800


# 10. SAML SETTINGS
# 11. LOGGING SETTINGS
# 12. SESSIONS SETTINGS

SESSION_ENGINE = 'django.contrib.sessions.backends.cache'


# 13. DATA UPLOAD SETTINGS
